# Generated by Django 2.0.4 on 2018-04-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullnode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='last_heard_from',
        ),
    ]
