# Generated by Django 2.0.4 on 2018-04-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullnode', '0003_node_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Node',
            new_name='Peer',
        ),
    ]
